name: GitHub Actions Speedy Net
on: [push]
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-18.04', 'ubuntu-latest']
        postgresql-version: ['13']
        is-master-or-staging:
          - ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging' }}
        exclude:
          - os: 'ubuntu-18.04'
            postgresql-version: 'latest'
    steps:
      - run: apt list --installed | grep postgresql
      - run: docker ps
      - run: pg_lsclusters
      - run: sudo service --status-all
