name: GitHub Actions Speedy Net
on: [push]
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-18.04', 'ubuntu-latest']
        postgresql-version: ['13']
        is-master-or-staging:
          - ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging' }}
        exclude:
          - os: 'ubuntu-18.04'
            postgresql-version: 'latest'
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - run: |
          docker ps
          pg_lsclusters
          sudo service postgresql status
          sudo service postgresql stop
          sudo service postgresql status
          pg_lsclusters
          docker ps
        if: ${{ matrix.postgresql-version != 'latest' }}
