name: GitHub Actions Speedy Net
on: [push]
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-18.04', 'ubuntu-latest']
        postgresql-version: ['13']
        is-master-or-staging:
          - ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging' }}
        exclude:
          - os: 'ubuntu-18.04'
            postgresql-version: 'latest'
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - run: apt list --installed | grep postgresql
      - run: |
          sudo apt-get -y remove postgresql-14 postgresql-client-14
          sudo pg_dropcluster 14 main
          ! docker stop $(docker ps -q --filter ancestor=postgres)
      - run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get -y install postgresql-${{ matrix.postgresql-version }}
      - run: grep 'port =' /etc/postgresql/${{ matrix.postgresql-version }}/main/postgresql.conf
      - run: docker ps
      - run: pg_lsclusters
      - run: sudo service --status-all
